### ISSUE TITLE
Lacking documentation / missing information

### ISSUE THREAD

**Issue by jkernagis2** [gitana/alpaca#190]
The documentation needs to be more thorough in general...

As a specific example, the 'noneLabel' option for select fields is not listed under the options documentation.  It is literally only mentioned at the bottom of the page in the last code example.  I only found it there with Ctrl+F, and that was after I had found the option being used in the alpaca source code when I started looking to see how to implement such functionality myself.

See: http://www.alpacajs.org/docs/fields/select.html

Update: Additionally, probably the worst thing that I've been dealing with is the next to non-existent information on what javascript libraries are required for various pieces of functionality to work.

The examples pages claim that simply running this:
$("#field1").alpaca({
    "data": "",
    "schema": {
        "format": "phone"
    }
});

will produce a field with masked input.  However, nowhere is it mentioned that you need to load jquery.maskedinput.min.js for this to work.  As it is, I'm being forced to inspect the javascript libraries that are loaded on the examples page, and pick out which ones are probably required for the basic functionality shown in the examples to work.

**Comment by uzquiano** [comment]
Thanks for the feedback.  I added the documentation for noneLabel and a few other items that were missing.  In addition, there were some cosmetic improvements to the schema and options tables to sort property keys, making things a little easier to find.

The documentation is getting better all the time, mostly driven by questions and issues raised like the one you supplied here.  Thank you for this!  We're open to documentation pull requests from the community if anyone has something specific they want to throw into the mix.  Alpaca has a pretty deep code base and lots of features.  There's a lot we can improve upon and documentation is one area where we always wish we could move faster.

Your point about third party libraries is spot on.  We're anticipating a move to using AMD in the build process to finely describe dependencies.  For example, the "text" field module could require the "typeahead" module.  It makes sense because then in the build you can optimize the requires and produce JS files of various sizes depending on what you want to include.

The problem with this is that many fields have optional modules.  The text field doesn't strictly require the "typeahead" field.  If it finds it, it uses it and so on.

While I like the technical merits of having everything well described via AMD, I think what you're pointing out is that the documentation field pages could include a section that lists out the exact optional dependencies (like maskedinput).  This makes a lot of sense to me.

With the next release (about to go out), I'm going to add the /lib directory to the distribution so that anyone installing from Bower or grabbing a download will have those assets.  For bower purists, this is overkill certainly, but for folks getting started, it is genuinely helpful.

Thanks for your comments.  I hope you don't mind my rambling train of thought as well!

**Comment by uzquiano** [comment]
The /lib directory is now included in the distribution.  "noneLabel" is covered.  I agree with the points on the documentation.  The docs, like the project, evolve as the project grows.  I'll close this and we'll keep plugging away at issues.  Please raise issues that specifically point to places we can improve the docs as well as the code.  Cheers!
