### ISSUE TITLE
template for array container object 

### ISSUE THREAD

**Issue by deviant32** [gitana/alpaca#199]
I am trying to change the container-object template of an array item in a form, however the code below won't apply the template to all items in the array.  It will only work if I apply it to /phone_numbers[0], but that obviously only applies the template to the first element.  Is there a way to apply the template to all elements in the array?

```javascript
  "view": {
    "parent": "array-list-no-image",
    "fields": {
        "/phone_numbers": {
            "templates": {
                "container-object": "./alpaca-templates/array-container-object-no-image.html"
            }
        }
    }
```

**Comment by uzquiano** [comment]
This has been fixed in head.  Pretty cool feature request, thanks for bringing it up.

You can build from master if you want.  There is a new example under the templates documentation.  You can now provide indexed-overrides (for example: /form/persons[2]/name) which apply to a specific index within an array as well as general all-purpose field overrides (for example: /form/persons/name) which apply to all indexes within an array.

We added a path matching lookup doodad which does it's best to find a tightest fit among any of the field-level overrides.  

This is a really nice feature.  Thanks for suggesting it.

Also, for anyone who goes this route in terms of customizing their forms, it's also strongly advised to take a look at custom views, fields or layouts as an even more flexible alternative.
