### ISSUE TITLE
FormBuilder demo not working in 1.5.8 (latest)

### ISSUE THREAD

**Issue by SuperSeb92** [gitana/alpaca#225]
Form builder shown here:

http://www.alpacajs.org/demos/form-builder/form-builder.html

Currently not working in Chrome/Firefox on OSX, currently unable to test this on anything but feel it may be the same issue regardless.

**Comment by lucas-m-acuna** [comment]
In the form-builder webpage there is an uncaught error, which is triggered when clicking on "delete"/"edit schema"/"edit options" buttons of the designer tab.

errors:
on delete -> "Cannot read property 'parent' of undefined."
on edit schema -> "Cannot read property 'getSchemaOfOptions' of undefined" 
on edit options -> "Cannot read property 'getSchemaOfSchema' of undefined" 

Change file form-builder.js, on function doRefresh(), in line 165, var alpacaFieldId. 

This is a pretty small change to get the id of each element and not the id of the main container, otherwise alpacaFieldId in these functions is "undefined" because it tries to reach the field.parent of the container. (you could choose other child class, but this is working for me).

var alpacaFieldId = $(this).children('.form-group').data("alpaca-field-id");

Great Job!! Alpaca Team. This library is wonderfull.

**Comment by uzquiano** [comment]
Yes, the problem you identified was exactly the issue and arose as a result of the new object containment model.  I believe this is fixed on the master branch (which is a preview of 1.5.9).  Can you try a build from master and see?  Otherwise, we should have this fixed in the 1.5.9 release (next up).

**Comment by SuperSeb92** [comment]
Just pulled down master, still seeing this issue

**Comment by uzquiano** [comment]
Fixed in head
