### ISSUE TITLE
Please update Release Notes

### ISSUE THREAD

**Issue by fredt34** [gitana/alpaca#276]
What's new ? I've seen that Alpaca had moved to 1.5.0, but I couln't find out what's been added... Can you please update https://github.com/gitana/alpaca/wiki/Release-Notes - or have brief explanations on the main web site ?

Thanks for all this nice job, and thanks for addressing this request !

Fred

**Comment by uzquiano** [comment]
Hi Fred,

The project moved to 1.5.0 over a year ago and we're now 11 releases in.  The release notes wiki page should probably be removed since we're no longer maintaining that.  The GitHub commit history provides a pretty exact idea of what changes went in and when down to the individual lines of code.  We've also taken to tagging releases within GitHub so that people can perform diffs between any release commits at any time.

Furthermore, the web site was completely redone to feature some pretty improved documentation.  It's worlds better than it used to be and provides some pretty thick chapters on templating, views, forms, wizards and more.

I hope that helps.  I don't see us doing release notes at this point since it's redundant.  We could possibly generate them automatically but it'd consist of little more than a repeat of the commit history in an abbreviated format.
