### ISSUE TITLE
Help - Incorrect field rendering across different browsers

### ISSUE THREAD

**Issue by nmangwanda** [gitana/alpaca#306]
Hi there

Please advise why fields are rendering in the incorrect order on Chrome but fine on IE and Firefox.
Have a look at the below link on the different browsers:

https://jsfiddle.net/atxdc19q/

Password field should be rendered below "Product" at the bottom.

**Comment by uzquiano** [comment]
This is because the default Alpaca render simply walks the JSON object keys in whatever order the browser hands them back.  JSON doesn't require keys to be in any particular order.  Some browsers may do things one way and others another way.  You're never guaranteed the order.  That's a JSON thing, not an Alpaca thing.

If you want to ensure the order, use the "order" option and specify the order.  Or use an options.sort function.  Alpaca will respect either of those.
