### ISSUE TITLE
Table data gets disordered when there are more than 10 columns

### ISSUE THREAD

**Issue by jgpelaez** [gitana/alpaca#310]
Table data gets disordered when there are more than 10 columns. I´ve written a codepen:

http://codepen.io/jgpelaez/full/YyWJxW
http://codepen.io/jgpelaez/pen/YyWJxW

It´s possible to see some columns not in the correct place and correct data, for example active has "title1" as data. If we remove some of the columns it works fine.

**Comment by uzquiano** [comment]
As best I can tell, this is related to:
https://github.com/gitana/alpaca/issues/298

The underlying issue seems to simply be that JSON object properties do not have guaranteed orders.  It's browser dependent to maintain the natural order of keys.  It seems that for less than 10 keys, the browser (in my case Chrome) may elect to preserve order but for larger numbers of keys, the order iterating order can change.

For example, we do things like:
for (var k in keys) { ... }

This order can change and it appears to affect both cases.

The workaround as noted in the linked issue is the use an explicit per-field option.order to force the order as you desire.  This will certainly work and should work for the table case here as well.

I'd be curious if you could try this using a build from head.  For the linked issue, this appears to work better on the latest code base (not-released).  We've enhanced some of the sort handling.

**Comment by uzquiano** [comment]
I'll close this.  The recommendation is explicit options.order on the fields.  You could also use a custom sort function.  There isn't a good way around this as the JSON key order is browser dependent.
