### ISSUE TITLE
Options window of Form Builder GUI broken with 1.5.14 release

### ISSUE THREAD

**Issue by cniesen** [gitana/alpaca#313]
Trying to access the options (wrench icon) of a Field in the Form Builder causes a JavaScript error "Unable to find field class for type: undefined".   This was working with the prior 1.5.13 release.

The cause for this is "Sort Function" option that has been added to the schema but not the option in ControlField.js.
See commit:
https://github.com/gitana/alpaca/commit/56d53826612b900ee9277653747aac2c10cb22f6#diff-0aac6a081506661d3cd961f8cb71a559R737

I found two potential solutions:
1) Add an option entry for the sort
```
        getOptionsForOptions: function() {
            return Alpaca.merge(this.base(), {
                "fields": {
                    "name": {
                        "type": "text"
                    },
                    "sort": {
                        "type": "text"
                    }
                }
            });
        }
```
2) Register the defaultSchemaFieldMapping for function in the TextField.js
```Alpaca.registerDefaultSchemaFieldMapping("function", "text");```

The second option seems to be better since functions are used in other places as well (e.g. UploadField.js)

**Comment by cniesen** [comment]
Pull request #314 created.

**Comment by uzquiano** [comment]
Thanks for this.  I took a look and decided to make it so that the form builder strips out form options of type "function".

The reason for this - Alpaca is JSON Schema compliant and "function" isn't a serializable type in JSON.  Thus, while we allow for functions to be plugged onto the config in places, it isn't something that we want to support within Alpaca's default schema mappings.  I'd rather enforce that functions should be stripped from schema configs ahead of rendering than introduce support for "function" as a serializable type.

Perhaps I'm wrong.  But for the moment, I made it so that the form builder removes the "sort" option ahead of rendering.  This seems to work well.

Thanks for putting as much thought into this.  Your suggestions were good ones.  In this case, I simply felt it could be done better by enforcing the strict reliance on JSON types.  What do you think?
