### ISSUE TITLE
Token field support

### ISSUE THREAD

**Issue by KarthikRama** [gitana/alpaca#327]
Hi,

Is it possible to add Token Field support for text boxes (with typeahead) in Alpaca.js similar to : http://sliptree.github.io/bootstrap-tokenfield/ ?

thanks,
Karthik

**Comment by uzquiano** [comment]
That's a great idea.  Sounds like a good candidate for a pull request! :)

If you're interested in contracting someone for formal development, write to support@cloudcms.com and we can connect you with someone to build it out.

**Comment by KarthikRama** [comment]
Thanks uzquiano. I just sent an email to support@cloudcms.com. 

I am new to this forum. Would you be able to brief me on how this pull request works?

**Comment by cniesen** [comment]
Pull request basically means that you implement the feature (do the coding) and offer it back to the project.

For more details: https://guides.github.com/activities/contributing-to-open-source/#contributing

**Comment by uzquiano** [comment]
There is an early cut in master as we needed it for one of our customers.  It is the "token" field type.  It might be close to what you're looking for.  If not, feel free to post feature requests so that someone in the community can make improvements if they wish.  Or write to support@cloudcms.com with a request and we can always get you an estimate.
