### ISSUE TITLE
How to add multiple validators for a given field?

### ISSUE THREAD

**Issue by sloria** [gitana/alpaca#345]
Is there a way to add multiple custom validators to a single field?

I see from http://www.alpacajs.org/docs/api/validation.html that `callback` may be called with multiple messages, but I want to add multiple validation functions to a field.

Here is an example use case:

```js
function isValidBev(callback) {
    var value = this.getValue();
    if (value == "beer" || value == "wine") {
        callback({
            "status": false,
            "message": "Not a valid beverage."
        });
    }
}

function isOfAge(callback) {
    var value = this.getValue();
    if (value < 21) {
        callback({
            "status": false,
            "message": "You are too young to drink alcohol!"
        });
    }
}


// ...

    "options": {
        "fields": {
            "password": {
                "label": "Your password",
                "validator": [isValidBev, isOfAge]
            }
        }
    }
```

**Comment by uzquiano** [comment]
That's a good idea.  In my experience, however, the problem with introducing support for multiple validators is that you then get into combinatorial logic problems.  And once you get into that, you get into a situation where you can begin to over-architect.

For example, in your array approach above, the logic seems to be A && B === true.  We could implement that.  But the moment we do, someone will say, "okay, but in my case, I want (A && B) || C === true, etc.  Or A || (B && !C) || D... and so on.

One is tempted to introduce some kind of proprietary logic expression syntax so that people can chain together function calls and then write a parser and processor.  However, at best this seems to only duplicate what JavaScript already does perfectly well.  Thus, the second option - just allow for JS functions so that developers can really do whatever they want.

I would recommend you have a single validation function callback and that you use that callback to hook into your discrete logic in whatever order you choose.

Any feedback from the community here is welcome.  I could be totally wrong (I often am).  What do you guys think?

**Comment by sloria** [comment]
Those are good points.

I think "and"-ing the validators (`A && B && C &* ...`) meets users' expectations. After all, built-in validators such min/max-length get combined with custom validators this way.

That said, I would understand if the maintainers want to put the responsibility of combining validators on the user.

**Comment by uzquiano** [comment]
Yeah, the combining of validators - for the moment - still falls on the developer.  We simply provide a hook so that you can fire into a function to handle things.  The function is async so that you can take your time doing the validation, maybe checking a registry, maybe calling remote endpoints, etc.  I think that leaves things pretty flexible and is probably as far as we want to go at the moment.
