### ISSUE TITLE
Version Changelog?

### ISSUE THREAD

**Issue by ambischof** [gitana/alpaca#346]
Where can I find the change log? The git tags have no information as to changes.

**Comment by cniesen** [comment]
With GitHub you can simply compare two releases.  To do so start creating a pull request by clicking the "new pull request" button on the github project home page. Change the "base" to the older release and the "compare" to the newer release numbers (i.e. 1.5.14 and 1.5.15).   Now you are able to see what commits have been applied to 1.5.15 that weren't part of 1.5.14.  You can also see what files changed and see the diff.  

This will generate the following URL (yes, you could just change the url to the versions you are interested): https://github.com/gitana/alpaca/compare/1.5.14...1.5.15

Since all lib dependencies were touched there are a lot of files that were changed.  So have fun looking though them. ;)

**Comment by ambischof** [comment]
I know how compare versions, and that exactly why I was hoping there was a change log! I might as well shuffle through 5 filing cabinets.

**Comment by uzquiano** [comment]
This would be useful but it's not something we're producing as part of the project at the moment.  The commit and PR history between releases is the source of record here.  If anyone wants to contribute release notes or a change log, please do.
